### ISSUE TITLE
Accessory not responding after some time

### ISSUE THREAD

**Issue by MirceaIs** [maximkulkin/esp-homekit-demo#132] opened 2018-09-19 20:44 UTC
Hello,

First of all, thank you to all contributors for sharing this library.
 
my setup:
latest version of homekit and dependinces cloned
M5Stack board / ESP32
iPhone X
tried two different setups: thermostat and temperature sensor.

I'm able to establish the pairing and install the accessory in my Home application, in a few minutes the accessory is not responding. After accessory restart all works fine for a few more minutes.
My implementation is similar with the one in the temperature sensor example, see below:

homekit_characteristic_t temperature = HOMEKIT_CHARACTERISTIC_(CURRENT_TEMPERATURE, 0);
homekit_characteristic_t humidity    = HOMEKIT_CHARACTERISTIC_(CURRENT_RELATIVE_HUMIDITY, 0);

void thermostat_identify(homekit_value_t _value) {
    ESP_LOGI("HOMEKIT","Thermostat identify");
}

homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_thermostat, .services=(homekit_service_t*[]) {
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Thermo"),
            HOMEKIT_CHARACTERISTIC(MANUFACTURER, "Mir"),
            HOMEKIT_CHARACTERISTIC(SERIAL_NUMBER, "001"),
            HOMEKIT_CHARACTERISTIC(MODEL, "MyThermo"),
            HOMEKIT_CHARACTERISTIC(FIRMWARE_REVISION, "0.1"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, thermostat_identify),
            NULL
        }),
        HOMEKIT_SERVICE(TEMPERATURE_SENSOR, .primary=true, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Temperature Sensor"),
            &temperature,
            NULL
        }),
        HOMEKIT_SERVICE(HUMIDITY_SENSOR, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "Humidity Sensor"),
            &humidity,
            NULL
        }),
        NULL
    }),
    NULL
};

homekit_server_config_t homekit_config = {
    .accessories = accessories,
    .password = "111-11-111"
};

homekit_config is sent as parameter to the homekit_server_init function called in SYSTEM_EVENT_STA_GOT_IP event. temperature and humidity characteristics are updates every 30s in a different thread. 

I wonder what am I doing wrong?

**Comment by maximkulkin** [comment] 2018-09-19 22:18
There are people reporting that problem but I can not reproduce it on any of my devices (I use NodeMCU devices from HiLetgo and Makerfocus and a Sonoff Dual R2). If you could collect and post debug logs (with HOMEKIT_DEBUG=1) of devices when they become unavailable that could help nailing that issue.

**Comment by MirceaIs** [comment] 2018-09-20 18:59
Hello,

Below the debug logs of my accessory device.
Between the last two lines in the log there is a time interval of up to a minute or longer. First I get the "not responding" message in Home app at random timing (range of minutes) after the last "Finished processing" line appears in console. "Closing client connection" massage comes about 1min after "not responding" in the app. 

I would expect that after "Closing client connection" message, a Home app restart resumes the connection but it doesn't.

I also disabled any other tasks to avoid race conditions or memory problems.

see log below:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0010,len:4
load:0x3fff0014,len:4848
ho 0 tail 12 room 4
load:0x40078000,len:8000
load:0x40080400,len:5548
entry 0x400806d4
I (182) boot: ESP-IDF v3.2-dev-773-gb999d10e-dirty 2nd stage bootloader
I (183) boot: compile time 19:35:27
I (188) boot: Enabling RNG early entropy source...
I (205) boot: SPI Speed      : 40MHz
I (218) boot: SPI Mode       : DIO
I (230) boot: SPI Flash Size : 4MB
I (243) boot: Partition Table:
I (254) boot: ## Label            Usage          Type ST Offset   Length
I (277) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (300) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (324) boot:  2 factory          factory app      00 00 00010000 00100000
I (347) boot: End of partition table
I (360) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x181e0 ( 98784) map
I (595) esp_image: segment 1: paddr=0x00028208 vaddr=0x3ffb0000 size=0x031a8 ( 12712) load
I (625) esp_image: segment 2: paddr=0x0002b3b8 vaddr=0x3ffb31a8 size=0x00000 (0) load
I (627) esp_image: segment 3: paddr=0x0002b3c0 vaddr=0x40080000 size=0x00400 (1024) load
I (653) esp_image: segment 4: paddr=0x0002b7c8 vaddr=0x40080400 size=0x04848 ( 18504) load
I (722) esp_image: segment 5: paddr=0x00030018 vaddr=0x400d0018 size=0x7bed0 (507600) map
I (1784) esp_image: segment 6: paddr=0x000abef0 vaddr=0x40084c48 size=0x0a53c (42300) load
I (1888) esp_image: segment 7: paddr=0x000b6434 vaddr=0x400c0000 size=0x00000 (0) load
I (1890) esp_image: segment 8: paddr=0x000b643c vaddr=0x50000000 size=0x00000 (0) load
I (1966) boot: Loaded app from partition at offset 0x10000
I (1966) boot: Disabling RNG early entropy source...
I (1968) cpu_start: Pro cpu up.
I (1979) cpu_start: Starting app cpu, entry point is 0x40080e2c
I (1) cpu_start: App cpu up.
I (2012) heap_init: Initializing. RAM available for dynamic allocation:
I (2033) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (2052) heap_init: At 3FFB9988 len 00026678 (153 KiB): DRAM
I (2071) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (2091) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (2111) heap_init: At 4008F184 len 00010E7C (67 KiB): IRAM
I (2130) cpu_start: Pro cpu start user code
I (39) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (40) MAIN: Hello Thermostat!
I (90) wifi: wifi driver task: 3ffc1228, prio:23, stack:3584, core=0
I (90) wifi: wifi firmware version: ece97c4
I (90) wifi: config NVS flash: enabled
I (90) wifi: config nano formating: disabled
I (90) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (100) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (130) wifi: Init dynamic tx buffer num: 32
I (130) wifi: Init data frame dynamic rx buffer num: 32
I (130) wifi: Init management frame dynamic rx buffer num: 32
I (140) wifi: Init static rx buffer size: 1600
I (140) wifi: Init static rx buffer num: 10
I (140) wifi: Init dynamic rx buffer num: 32
I (210) phy: phy_version: 3960, 5211945, Jul 18 2018, 10:40:07, 0, 0
I (210) wifi: mode : sta (80:7d:3a:c4:54:c4)
I (210) MAIN: Connecting to Wifi.
I (1550) wifi: n:11 0, o:1 0, ap:255 255, sta:11 0, prof:1
I (2390) wifi: state: init -> auth (b0)
I (2400) wifi: state: auth -> assoc (0)
I (2400) wifi: state: assoc -> run (10)
I (2440) wifi: connected with MMI_Net, channel 11
I (2440) wifi: pm start, type: 1

I (3590) event: sta ip: 192.168.0.11, mask: 255.255.255.0, gw: 192.168.0.1
I (3590) MAIN: Got IP:192.168.0.11
I (3590) MAIN: Initializing HomeKit accesory.
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: 52:19:1A:11:04:9F
>>> HomeKit: Found admin pairing with 9B957BAC-CCDD-4380-86DA-DAFE7BFCFC5A, disabling pair setup
>>> HomeKit: Configuring mDNS
>>> homekit_run_server: Staring HTTP server
>>> HomeKit: Got new client connection: 55
>>> homekit_client_process: [Client 55] Got 157 incomming data
>>> homekit_server_on_pair_verify: HomeKit Pair Verify
>>> homekit_server_on_pair_verify: Free heap: 219056
>>> tlv_debug: Got following TLV values:
>>> tlv_debug: Type 3 value (32 bytes): \xC6\xFB\xB1\xBBXH\xE46\xC7\xB9*\x9B%\xE16\xF0\xB7K\xFD\xAB\xE2~\x01\xE1\xC5\x0E\xA6+Mr\x85E
>>> tlv_debug: Type 6 value (1 bytes): \x01
>>> HomeKit: [Client 55] Pair Verify Step 1/2
>>> homekit_server_on_pair_verify: [Client 55] Importing device Curve25519 public key
>>> homekit_server_on_pair_verify: [Client 55] Generating accessory Curve25519 key
>>> homekit_server_on_pair_verify: [Client 55] Exporting accessory Curve25519 public key
>>> homekit_server_on_pair_verify: [Client 55] Generating Curve25519 shared secret
>>> homekit_server_on_pair_verify: [Client 55] Generating signature
>>> homekit_server_on_pair_verify: [Client 55] Generating proof
>>> homekit_server_on_pair_verify: [Client 55] Encrypting response
>>> send_tlv_response: [Client 55] Sending TLV response
>>> tlv_debug: Got following TLV values:
>>> tlv_debug: Type 5 value (101 bytes): \xA5v\xED:Df\xE5\xCD\xC4\xF1\x1C\x900$\xB5\xAC1_\xC8\xB6z\xBC\x86\x06Y\xCD\xA9\x9D?\xE6\xDC'\x9A\x94f\x0BrsL\x87[.\x10\xF7\x85=\xC8\xDF\xF38\x127;lK\x8E4\x96:\x8B\x97'\\\xE4\xC9h\x15L<f\x1C\x9AGK<]eW?\x8A\xB5\xB9i\xB4\xF2                                          \x0F\xB7\xED\xCDb$^\xEA\x0Eg'\x912g\xA6w
>>> tlv_debug: Type 3 value (32 bytes): \x95K\x1A.\x95\x02\x120\xD37T\x15s\xCAQ+\xE2\xA8h\x8Bk\x99\x94zD\x1AM\xAC\xEC>\xD4\x18
>>> tlv_debug: Type 6 value (1 bytes): \x02
>>> client_send: [Client 55] Sending payload: HTTP/1.1 200 OK\x0D\x0AContent-Type: application/pairing+tlv8\x0D\x0AContent-Length:140\x0D\x0AConnection: keep-alive\x0D\x0A\x0D\x0A\x05e\xA5v\xED:Df\xE5\xCD\xC4\xF1\x1C\x900$\xB5\xAC1_\xC8\xB6z\xBC\x86\x06Y\xCD\xA                                          9\x9D?\xE6\xDC'\x9A\x94f\x0BrsL\x87[.\x10\xF7\x85=\xC8\xDF\xF38\x127;lK\x8E4\x96:\x8B\x97'\\\xE4\xC9h\x15L<f\x1C\x9AGK<]eW?\x8A\xB5                                          \xB9i\xB4\xF2\x0F\xB7\xED\xCDb$^\xEA\x0Eg'\x912g\xA6w\x03 \x95K\x1A.\x95\x02\x120\xD37T\x15s\xCAQ+\xE2\xA8h\x8Bk\x99\x94zD\x1AM\xAC                                          \xEC>\xD4\x18\x06\x01\x02
>>> homekit_client_process: [Client 55] Finished processing
>>> homekit_client_process: [Client 55] Got 246 incomming data
>>> homekit_server_on_pair_verify: HomeKit Pair Verify
>>> homekit_server_on_pair_verify: Free heap: 218780
>>> tlv_debug: Got following TLV values:
>>> tlv_debug: Type 6 value (1 bytes): \x03
>>> tlv_debug: Type 5 value (120 bytes): \x83 \x14\xF7i\xCFt#\xEBU\x0F\x84\xAC:\xCC\xF5\xAF\xDC\xFBb\x1\xF4\x19\xDCgd\xFA\x8D\x91|\xD\xD63\xF7iE\xC4R\x83h\x82\xAFeD,U#\x08e\x18p]l\\\x9E\x94E\xFB\x17s\x95~a\x8D\xC5\x94\x05U\xD0\xCD\x90\xB1\xB0\xE2\xF8\xE7\xF8\xCA                                          \xB2\xF6\x0F-9\xC4>\x98\xA0*\xFC\xB1[$\x9FtaV\xB3\xCB8c\xA6\xEb.36i\x84\xB6\xBEN\xCEl\xFB\x1B\xDB\x1C
>>> HomeKit: [Client 55] Pair Verify Step 2/2
>>> homekit_server_on_pair_verify: [Client 55] Decrypting payload
>>> homekit_server_on_pair_verify: [Client 55] Searching pairing with 9B957BAC-CCDD-4380-86DA-DAFE7BFCFC5A
>>> HomeKit: [Client 55] Found pairing with 9B957BAC-CCDD-4380-86DA-DAFE7BFCFC5A
>>> homekit_server_on_pair_verify: [Client 55] Verifying device signature
>>> send_tlv_response: [Client 55] Sending TLV response
>>> tlv_debug: Got following TLV values:
>>> tlv_debug: Type 6 value (1 bytes): \x04
>>> client_send: [Client 55] Sending payload: HTTP/1.1 200 OK\x0D\x0AContent-Type: application/pairing+tlv8\x0D\x0AContent-Length:3\x0D\x0AConnection: keep-alive\x0D\x0A\x0D\x0A\x06\x01\x04
>>> HomeKit: [Client 55] Verification successful, secure session established
>>> homekit_client_process: [Client 55] Finished processing
>>> homekit_client_process: [Client 55] Got 77 incomming data
>>> homekit_client_process: [Client 55] Decrypting data
>>> homekit_client_process: [Client 55] Decrypted 59 bytes, available 0
Decrypted data (59 bytes): "GET /accessories HTTP/1.1\x0D\x0AHost: Thermo._hap._tcp.local\x0D\x0A\x0D\x0A"
>>> HomeKit: [Client 55] Get Accessories
>>> homekit_server_on_get_accessories: Free heap: 218960
>>> client_send: [Client 55] Sending payload: HTTP/1.1 200 OK\x0D\x0AContent-Type: application/hap+json\x0D\x0ATransfer-Encoding: chunked\x0D\x0AConnection: keep-alive\x0D\x0A\x0D\x0A
>>> client_send: [Client 55] Sending payload: 3fa\x0D\x0A{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","hidden":false,"primary":false,"characteristics":[{"aid":1,"iid":2,"type":"00000023-0000-1000-8000-0026BB765291",                                          "perms":["pr"],"description":"Name","format":"string","value":"Thermo"},{"aid":1,"iid":3,"type":"00000020-0000-1000-8000-0026BB7652                                          91","perms":["pr"],"description":"Manufacturer","format":"string","value":"Mir"},{"aid":1,"iid":4,"type":"00000030-0000-1000-8000-0                                          026BB765291","perms":["pr"],"description":"Serial Number","format":"string","value":"001"},{"aid":1,"iid":5,"type":"00000021-0000-1                                          000-8000-0026BB765291","perms":["pr"],"description":"Model","format":"string","value":"MyThermo"},{"aid":1,"iid":6,"type":"00000052                                          -0000-1000-8000-0026BB765291","perms":["pr"],"description":"Firmware Revision","format":"string","value":"0.1"},{"aid":1,"iid":7,"t                                          ype":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"description":"Identify","format":"bool"}]},{"iid":8,"type":"0000008A-00                                          00-1000-8000-0026BB765291",\x0D\x0A
>>> client_send: [Client 55] Sending payload: 38f\x0D\x0A"hidden":false,"primary":true,"characteristics":[{"aid":1,"iid":9,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"description":"Name","format":"string","value":"Temperature Sensor"},{"aid":1,                                          "iid":10,"type":"00000011-0000-1000-8000-0026BB765291","perms":["pr","ev"],"ev":false,"description":"Current Temperature","format":                                          "float","unit":"celsius","minValue":0,"maxValue":100,"minStep":0.100000001490116,"value":0}]},{"iid":11,"type":"00000082-0000-1000-                                          8000-0026BB765291","hidden":false,"primary":false,"characteristics":[{"aid":1,"iid":12,"type":"00000023-0000-1000-8000-0026BB765291                                          ","perms":["pr"],"description":"Name","format":"string","value":"Humidity Sensor"},{"aid":1,"iid":13,"type":"00000010-0000-1000-800                                          0-0026BB765291","perms":["pr","ev"],"ev":false,"description":"Current Relative Humidity","format":"float","unit":"percentage","minV                                          alue":0,"maxValue":100,"minStep":1,"value":0}]}]}]}\x0D\x0A
>>> client_send: [Client 55] Sending payload: 0\x0D\x0A\x0D\x0A
>>> homekit_client_process: [Client 55] Finished processing
>>> homekit_client_process: [Client 55] Got 94 incomming data
>>> homekit_client_process: [Client 55] Decrypting data
>>> homekit_client_process: [Client 55] Decrypted 76 bytes, available 0
Decrypted data (76 bytes): "GET /characteristics?id=1.10,1.13 HTTP/1.1\x0D\x0AHost: Thermo._hap._tcp.local\x0D\x0A\x0D\x0A"
>>> HomeKit: [Client 55] Get Characteristics
>>> homekit_server_on_get_characteristics: Free heap: 218624
>>> homekit_server_on_get_characteristics: [Client 55] Query paramter id = 1.10,1.13
>>> homekit_server_on_get_characteristics: [Client 55] Requested characteristic info for 1.10
>>> homekit_server_on_get_characteristics: [Client 55] Requested characteristic info for 1.13
>>> client_send: [Client 55] Sending payload: HTTP/1.1 200 OK\x0D\x0AContent-Type: application/hap+json\x0D\x0ATransfer-Encoding: chunked\x0D\x0AConnection: keep-alive\x0D\x0A\x0D\x0A
>>> homekit_server_on_get_characteristics: [Client 55] Requested characteristic info for 1.10
>>> homekit_server_on_get_characteristics: [Client 55] Requested characteristic info for 1.13
>>> client_send: [Client 55] Sending payload: 4f\x0D\x0A{"characteristics":[{"aid":1,"iid":10,"value":0},{"aid":1,"iid":13,"value":0}]}\x0D\x0A
>>> client_send: [Client 55] Sending payload: 0\x0D\x0A\x0D\x0A
>>> homekit_client_process: [Client 55] Finished processing
>>> homekit_client_process: [Client 55] Got 216 incomming data
>>> homekit_client_process: [Client 55] Decrypting data
>>> homekit_client_process: [Client 55] Decrypted 198 bytes, available 0
Decrypted data (198 bytes): "PUT /characteristics HTTP/1.1\x0D\x0AHost: Thermo._hap._tcp.local\x0D\x0AContent-Length: 79\x0D\x0AContent-Type: application/hap+json\x0D\x0A\x0D\x0A{"characteristics":[{"aid":1,"iid":10,"ev":true},{"aid":1,"iid":13,"ev":true}]}"
>>> HomeKit: [Client 55] Update Characteristics
>>> homekit_server_on_update_characteristics: Free heap: 218656
>>> homekit_server_on_update_characteristics: [Client 55] Processing element {
        "aid":  1,
        "iid":  10,
        "ev":   true
}
>>> homekit_server_on_update_characteristics: [Client 55] Processing element {
        "aid":  1,
        "iid":  13,
        "ev":   true
}
>>> homekit_server_on_update_characteristics: [Client 55] There were no processing errors, sending No Content response
>>> client_send: [Client 55] Sending payload: HTTP/1.1 204 No Content\x0D\x0A\x0D\x0A
>>> homekit_client_process: [Client 55] Finished processing
>>> homekit_client_process: [Client 55] Got 216 incomming data
>>> homekit_client_process: [Client 55] Decrypting data
>>> homekit_client_process: [Client 55] Decrypted 198 bytes, available 0
Decrypted data (198 bytes): "PUT /characteristics HTTP/1.1\x0D\x0AHost: Thermo._hap._tcp.local\x0D\x0AContent-Length: 79\x0D\x0AContent-Type: application/hap+json\x0D\x0A\x0D\x0A{"characteristics":[{"aid":1,"iid":10,"ev":true},{"aid":1,"iid":13,"ev":true}]}"
>>> HomeKit: [Client 55] Update Characteristics
>>> homekit_server_on_update_characteristics: Free heap: 218624
>>> homekit_server_on_update_characteristics: [Client 55] Processing element {
        "aid":  1,
        "iid":  10,
        "ev":   true
}
>>> homekit_server_on_update_characteristics: [Client 55] Processing element {
        "aid":  1,
        "iid":  13,
        "ev":   true
}
>>> homekit_server_on_update_characteristics: [Client 55] There were no processing errors, sending No Content response
>>> client_send: [Client 55] Sending payload: HTTP/1.1 204 No Content\x0D\x0A\x0D\x0A
>>> homekit_client_process: [Client 55] Finished processing
>>> HomeKit: [Client 55] Closing client connection

**Comment by ziolelle** [comment] 2018-11-22 08:21
Hi, the same for me, but sorry I have no log... 
I will investigate little more

**Comment by MirceaIs** [comment] 2018-11-22 10:09
Hello,

Just a short update...
I've found some problems with the mdns client I was using. The mdns implementation in the esp-idf master branch is buggy and it stops responding after a while. This might explain why my hk accessory wasn't responding. I compiled against a clean copy of IDF release v3.2 and now the mdns problem is solved. However i still get sporadically device not responding in the current implementation event with mdns responding. There seems to be one additional issue which I'll try to debug when I'll find some time.

**Comment by ziolelle** [comment] 2018-11-27 07:57
In my experience, it seems that it only on ESP32 implementation that it fails, the same (almost...) code for homekit project under ESP8266 implmentation doesn't suffer of this.
With last changes in EspressIF SDK the think is better but also for me, sometime the ESP32 is not responding.

**Comment by peros550** [comment] 2018-12-25 11:37
I have Wemos D1 mini failing as well. Has anybody found any solution?

**Comment by peros550** [comment] 2018-12-26 10:08
> I compiled against a clean copy of IDF release v3.2 and now the mdns problem is solved. 

Could you please provide some instructions how did you do that? I would like to give it a try. 

Thanks

**Comment by MirceaIs** [comment] 2018-12-26 11:13
Just clone esp-idf from release v3.2 branch here: 
https://github.com/espressif/esp-idf/tree/release/v3.2
This branch should contain a stable implementation of MDNS responder.
Make sure to compile your project against this version by updating IDF–PATH in your build environment.

**Comment by kvanbael** [comment] 2018-12-28 18:12
I have the same issue: ESP32, homekit 'not responding' after a few hours.
Thanks for the tip to try the ESP-IDF release/v3.2... but that doesn't seem to solve my problem.

**Comment by kvanbael** [comment] 2019-01-02 11:07
[Here](https://www.dropbox.com/s/ramog08qk2cw1el/esplog.txt?dl=0)'s a log of the issue with homekit debug info (ESP-IDF v3.2, ESP32 chip, several apple devices).

At the end of the log, at least 2 apple devices were showing the accessory as "not responding". Refreshing the Home app (bringing it to the background and foreground) didn't trigger any new log output.

I don't see anything suspicious on the log, except for the connections being closed. It seems like the issue is at another layer (mDNS?)

`>>> HomeKit: [Client 57] Closing client connection`
`>>> HomeKit: [Client 59] Closing client connection`

**Comment by bryantcoles** [comment] 2019-01-04 13:56
I have the exact same issue using the Temp Sensor example with a ESP8266-12E and  DHT22. Even with these problems, the work that has been done here is excellent. Is anyone aware of any other diy HomeKit development environments that we can test against?

**Comment by peros550** [comment] 2019-01-04 14:20
> I have the exact same issue using the Temp Sensor example with a ESP8266-12E and DHT22. Even with these problems, the work that has been done here is excellent. Is anyone aware of any other diy HomeKit development environments that we can test against?

Sure thing this is an excellent work. 

In regards to your questions, have a look in this also excellent repo>> https://github.com/RavenSystem/esp-homekit-devices

There is also a similar issue discussed here: https://github.com/RavenSystem/esp-homekit-devices/issues/130

I don't know if this issue is caused by the code being not very well optimized or because of another layer not performing as expected (i.e. TCP, mDNSs etc) or even because of bad wifi environment or settings.

**Comment by ziolelle** [comment] 2019-01-04 16:18
> I have the exact same issue using the Temp Sensor example with a ESP8266-12E and DHT22. Even with these problems, the work that has been done here is excellent. Is anyone aware of any other diy HomeKit development environments that we can test against?

There is also this repository, I didn't test it deeply
https://github.com/younghyunjo/esp32-homekit

**Closed** 2019-01-27 09:20 UTC
