### ISSUE TITLE
History graph like EVE homekit products

### ISSUE THREAD

**Issue by Martvvliet** [maximkulkin/esp-homekit-demo#226] opened 2019-06-12 19:48 UTC
Hi,

I was wondering how to enable the history in the homekit devices. WIth the EVE homekit app you can read out the history. This works with EVE product, but also with my flora sensor that I connected by Homebridge. I'm building an air quality sensor and I was wondering if it is possible to enable this with this software?

**Comment by maximkulkin** [comment] 2019-06-12 21:40
You need to accumulate history on accessory end and implement EVE's custom characteristics that will expose that history to EVE app.

**Comment by Martvvliet** [comment] 2019-06-13 05:59
Thanks for the response, are you familiar with these characteristics?

**Comment by maximkulkin** [comment] 2019-06-13 08:35
I'm not, but a quick google search gave this: https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d

**Comment by dezdeepblue** [comment] 2019-06-15 13:13
Duplicate of #121

**Closed** 2019-09-04 01:55 UTC
