### ISSUE TITLE
Request for a adjustment in  program for Sonoff Basic R3

### ISSUE THREAD

**Issue by sanilsdevan** [maximkulkin/esp-homekit-demo#351] opened 2020-05-22 19:50 UTC
Sonoff basic R3 (the latest sonoff basic) has wifi indicator led on GPIO13 and also another indicator led connected to relay on GPIO12. Is there any chance that the program can be modified so that the wifi indicator led turns off (or keeps blinking) if the device gets disconnected from wifi network? Also, the wifi indicator keeps on blinking at the initial stage until the device is configured & gets connected to the wifi network for the first time

**Comment by maximkulkin** [comment] 2020-05-22 22:53
Yes, it can be done

**Comment by maximkulkin** [comment] 2020-05-22 22:54
Duplicate of #352

**Closed by maximkulkin** 2020-05-22 22:54 UTC
